# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Configuration for development teams
language: "en-US"
reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    pmd:
      enabled: true
    markdownlint:
      enabled: true
    shellcheck:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  code_guidelines:
    enabled: true
