---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: dependency-words
    path: "./.cspell/dependency-words.txt"
    addWords: true
  - name: game-words
    path: "./.cspell/game-words.txt"
    addWords: true
  - name: project-words
    path: "./.cspell/project-words.txt"
    addWords: true
dictionaries:
  - dependency-words
  - game-words
  - project-words
ignorePaths:
  - "/.cspell"
  - "bin"
  - "obj"