name: Setup Environment
description: Sets up .NET and restores all binary dependencies, with caching.
inputs:
  token:
    description: GitHub token for downloading release artifacts and NuGet auth.
    required: true
runs:
  using: composite
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5

    - name: Cache Game-Lib
      id: cache-game-lib
      uses: actions/cache@v4
      with:
        path: game-lib
        key: ${{ runner.os }}-game-lib-${{ hashFiles('game-lib/version.workflow.info') }}

    - name: Cache UPM
      id: cache-upm
      uses: actions/cache@v4
      with:
        path: upm
        key: ${{ runner.os }}-upm-${{ hashFiles('upm/version.workflow.info') }}

    - name: Restore Binary Dependencies
      if: steps.cache-game-lib.outputs.cache-hit != 'true' || steps.cache-upm.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: dotnet build --no-restore -t:LF2RestoreBinaryDependencies

    - name: Setup NuGet Authentication
      shell: bash
      run: |
        echo "GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
