name: Setup Environment
description: Sets up .NET and restore
inputs:
  token:
    description: GitHub token for downloading release artifacts and NuGet auth.
    required: true
runs:
  using: composite
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        cache: true
        cache-dependency-path: projects/mods/**/packages.lock.json

    - name: Restore Nuget packages
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: dotnet restore --locked-mode
