name: Setup Environment
description: Sets up .NET and optionally restores NuGet packages.

inputs:
  token:
    description: GitHub token for NuGet auth. Defaults to the GITHUB_TOKEN.
    required: false
    default: ${{ github.token }}
  restore:
    description: Set to "false" to skip the dotnet restore step.
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        cache: ${{ inputs.restore == 'true' }}
        cache-dependency-path: projects/mods/**/packages.lock.json

    - name: Restore Nuget packages
      if: inputs.restore == 'true'
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: dotnet restore --locked-mode
