return {
	Title = "【测试】开局roll主角",
	Source = 0,
	FileId = 1,
	Version = "0.0.0.1",
	GameVersion = "0.0.79.50-test",
	Author = "我玩LF2",
	Description = "开局roll主角",
	TagList = {
		[1] = "Modifications",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	BackendPlugins = {
		[1] = "RollProtagonist.Backend.dll"
	},
	FrontendPlugins = {
		[1] = "RollProtagonist.Frontend.dll",
	},
	Cover = nil,
	WorkshopCover = nil,
}
