return {
	Title = "【测试】UniTask 支持",
	Source = 0,
	FileId = 1,
	Version = "0.0.0.1",
	GameVersion = "0.0.79.50-test",
	Author = "我玩LF2",
	Description = "为其他 Mod 提供 UniTask 的依赖支持；以及进行 UniTask 的初始化。",
	TagList = {
		[1] = "Frameworks",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	FrontendPlugins = {
		[1] = "UniTaskSupport.Frontend.dll",
	},
	NeedRestartWhenSettingChanged = false,
	Cover = nil,
	WorkshopCover = nil,
}
