return {
	Title = "【测试】UniTask 支持",
	Source = 0,
	FileId = 2,
	Version = "0.0.0.1",
	GameVersion = "0.0.78.49-test",
	Author = "我玩LF2",
	Description = "Mod 支持向；非面向玩家",
	TagList = {
		[1] = "Frameworks",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	FrontendPlugins = {
		[1] = "UniTaskSupport.Frontend/UniTaskSupport.Frontend.dll",
	},
	Cover = nil,
	WorkshopCover = nil,
}
