return {
	Title = "【测试】天意高难问",
	Source = 0,
	FileId = 5,
	Version = "0.0.0.1",
	GameVersion = "0.0.79.46-test",
	Author = "我玩LF2",
	Description = "天意高难问",
	WorkshopCover = nil,
	TagList = {
		[1] = "Optimizations",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	    BackendPlugins = {
        [1] = "Unfathomed.Backend.dll"
    },
	NeedRestartWhenSettingChanged = false,
}
