return {
	Title = "【测试】天意高难问",
	Source = 0,
	FileId = 3579569394,
	Version = "0.0.0.1",
	GameVersion = "0.0.79.47-test",
	Author = "我玩LF2",
	Description = "本 mod 专为补全太吾世界的运作设定而开发，目的是让太吾世界更为鲜活自由。\n目前补全的设定如下：\n\n【年龄补全】\n- 少侠也能喝茶酒\n- 化魂阁也能选中少侠\n- 界青也能谋杀少侠\n- 少侠死后也会有骸骨\n- 少侠在战败后也会有死劫\n- 少侠也能有魅力\n- 少侠也能尝试提高心情\n- 少侠也能获取历练\n- 少侠也会遭受侵袭\n- 生死关节也能选中少侠\n- 九死离魂手特效也能对少侠生效\n- 瑶姬云雨式特效也能对少侠生效\n- 血犼骷髅墓碑也能有少侠\n- 仙人泼墨也能影响到少侠\n- 三才目标也能有少侠\n- 伏龙坛事件也与少侠有关\n- 少侠也不会舍弃奇书\n- 天谴无人豁免\n- 少侠也能有门派特性\n- 峨眉事件也与少侠有关\n- 少侠入牢也要遭受刑罚\n- 少侠总能像大侠那样被选中\n- 村民少侠能早恋\n\n【玄灰补全】\n- 宝宝能为大爷承担部分玄灰名额\n- 少侠能为大叔承担部分玄灰名额\n- 玄灰最快在成年后发作\n\n【生育补全】\n- 避孕时考虑的是活着的血亲孩子而不是所有\n- 男性发起欺侮不考虑避孕；但不意味着必中。\n\n【概率补全】\n- 优化偏态分布的曲线，使其均值和标准差与参数相符；使得曲线更平滑。",
	TagList = {
		[1] = "Optimizations",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	BackendPlugins = {
		[1] = "Unfathomed.Backend.dll",
	},
	NeedRestartWhenSettingChanged = false,
	Cover = "unfathomed.jpg",
	WorkshopCover = "unfathomed.jpg",
}
