name: Build and Release

on:
  push:
    tags:
      - "mods/*/v*" # 匹配格式: mods/<mod-name>/v<version>
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

jobs:
  build-mod:
    if: startsWith(github.ref, 'refs/tags/mods/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse tag and set variables
        id: parse-tag
        run: |
          set -euo pipefail
          FULL_TAG="${GITHUB_REF#refs/tags/}"

          if [[ ! "$FULL_TAG" =~ ^mods/[^/]+/v[^/]+$ ]]; then
            echo "::error::Invalid tag format. Expected 'mods/<mod-name>/v<version>'";
            exit 1
          fi

          MOD_NAME="${FULL_TAG#mods/}"
          MOD_NAME="${MOD_NAME%%/*}"
          VERSION="${FULL_TAG##*/}"
          VERSION="${VERSION#v}"
          MOD_DIR="projects/mods/$MOD_NAME"

          echo "Parsed values:"
          echo "MOD_NAME=$MOD_NAME"
          echo "VERSION=$VERSION"
          echo "MOD_DIR=$MOD_DIR"

          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "full_tag=$FULL_TAG" >> $GITHUB_ENV
          echo "MOD_DIR=$MOD_DIR" >> $GITHUB_ENV

      - name: Read build configuration
        id: read-config
        run: |
          set -euo pipefail
          CONFIG_FILE="${{ env.MOD_DIR }}/mod.workflow.json"

          if [ ! -f "$CONFIG_FILE" ]; then
            echo "::error::Build configuration file not found at $CONFIG_FILE";
            exit 1
          fi

          PROJECTS=$(jq -r '.buildProjects | join(",")' "$CONFIG_FILE")

          if [ -z "$PROJECTS" ]; then
            echo "::error::No build projects defined in configuration";
            exit 1
          fi

          echo "PROJECTS=$PROJECTS" >> $GITHUB_ENV

      - name: Build projects
        run: |
          set -euo pipefail
          IFS=',' read -ra PROJECT_ARRAY <<< "${{ env.PROJECTS }}"
          BUILD_SUMMARY=""

          for project in "${PROJECT_ARRAY[@]}"; do
            PROJECT_PATH="${{ env.MOD_DIR }}/$project/$project.csproj"
            echo "Publishing project: $project"

            dotnet publish "$PROJECT_PATH" -c Release -p:Version=${{ env.VERSION }} \
              --verbosity minimal --nologo || {
                echo "::error::Publish failed for $project";
                exit 1;
              }

            PUBLISH_DIR=$(find "${{ env.MOD_DIR }}/$project/bin/Release" -type d -path "*/publish" | head -1)
            if [ -z "$PUBLISH_DIR" ]; then
              echo "::error::Publish directory not found for $project";
              exit 1;
            fi

            BUILD_SUMMARY+="• $project → $(basename $(dirname "$PUBLISH_DIR"))\n"
          done

          echo "BUILD_SUMMARY<<EOF" >> $GITHUB_ENV
          echo -e "$BUILD_SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p combined-artifacts
          IFS=',' read -ra PROJECT_ARRAY <<< "${{ env.PROJECTS }}"

          BUILD_DATE_ISO=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          BUILD_DATE_READABLE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          echo "BUILD_DATE_READABLE=$BUILD_DATE_READABLE" >> $GITHUB_ENV

          for project in "${PROJECT_ARRAY[@]}"; do
            PUBLISH_DIR=$(find "${{ env.MOD_DIR }}/$project/bin/Release" -type d -path "*/publish" | head -1)
            if [ -z "$PUBLISH_DIR" ]; then
              echo "::error::Publish directory not found for $project in artifact preparation";
              exit 1;
            fi

            PROJECT_ARTIFACT_DIR="combined-artifacts/$project"
            mkdir -p "$PROJECT_ARTIFACT_DIR"
            cp -r "$PUBLISH_DIR"/* "$PROJECT_ARTIFACT_DIR/"
          done

          cat > combined-artifacts/version.json <<EOF
          {
            "mod": "${{ env.MOD_NAME }}",
            "version": "${{ env.VERSION }}",
            "gameLib": "${{ env.LIB_VERSION }}",
            "buildDate": "$BUILD_DATE_ISO"
          }
          EOF

          ZIP_NAME="${{ env.MOD_NAME }}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          (cd combined-artifacts && zip -r "../${ZIP_NAME}" .)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.full_tag }}
          name: ${{ env.MOD_NAME }} v${{ env.VERSION }}
          body: |
            ### Build Summary
            ${{ env.BUILD_SUMMARY }}
            **Game Lib Version**: ${{ env.LIB_VERSION }}
            **Build Date**: ${{ env.BUILD_DATE_READABLE }}
          files: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-build-check:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build solution
        run: dotnet build lf2-taiwu-mods.slnx -c Release