name: On Merge Queue

on:
  merge_group:
    types: [checks_requested]

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Solution
        run: dotnet build -c Release

      - name: Upload Mod Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-build-artifacts-pr-${{ github.event.pull_request.number }}
          path: "projects/mods/**/bin/Release"
          retention-days: 7
