name: On Push to Master

on:
  push:
    branches:
      - master

jobs:
  update-template-branch:
    name: Update Template Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set Configuration
        id: config
        run: |
          echo "mods_dir=projects/mods" >> $GITHUB_OUTPUT
          echo "template_branch=template" >> $GITHUB_OUTPUT
          echo "commit_message=chore: update template from master" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          restore: false

      - name: Prepare Template Content
        run: |
          find ${{ steps.config.outputs.mods_dir }} -name "*.csproj" -print0 | xargs -0 -I {} dotnet sln remove {}
          find ${{ steps.config.outputs.mods_dir }} -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
          rm -f .github/workflows/push-to-master.yaml
          echo "" > ${{ steps.config.outputs.mods_dir }}/README.md
          echo "" > .cspell/project-words.txt

      - name: Push to Template Branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ steps.config.outputs.template_branch }}
          message: ${{ steps.config.outputs.commit_message }}
          fetch: false
          push: origin ${{ steps.config.outputs.template_branch }} --force
