name: On Push to Master

on:
  push:
    branches:
      - master

jobs:
  update-template-branch:
    name: Update Template Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      LF2_MODS_DIR: projects/mods
      LF2_TEMPLATE_BRANCH: template
      LF2_COMMIT_MESSAGE: "chore: update template from master"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5

      - name: Prepare Template Content
        run: |
          find ${{ env.LF2_MODS_DIR }} -name "*.csproj" -print0 | xargs -0 -I {} dotnet sln remove {}
          find ${{ env.LF2_MODS_DIR }} -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
          echo "" > ${{ env.LF2_MODS_DIR }}/README.md
          echo "" > .cspell/project-words.txt

      - name: Push to Template Branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ env.LF2_TEMPLATE_BRANCH }}
          message: ${{ env.LF2_COMMIT_MESSAGE }}
          fetch: false
          push: origin ${new_branch input} --force
